app/admin/routes.py
from flask import render_template, request, redirect, flash, session,Markup, jsonify, Blueprint, url_for
import werkzeug.utils
import pandas as pd
from werkzeug import url_encode
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy import func
from flask_login import login_user, current_user, logout_user, login_required
from app import app
from app.admin.forms import santri_F, admin_F, editadmin_F, loginadmin_F, editsantri_F, syariah_F
from app.models import Tusers, Tsantri, Tsyariah, Tajaran
from app import db, bcrypt

radmin = Blueprint('radmin', __name__)

@radmin.route('/', methods=['GET','POST'])
def index():
    form = loginadmin_F()
    return render_template("index.html", form=form)

@radmin.route('/dashboard')
@login_required
def dashboard():
    santri = Tsantri.query.count()
    laki = Tsantri.query.filter_by(jenis_k="Laki-Laki").count()
    cewe = Tsantri.query.filter_by(jenis_k="Perempuan").count()
    bayar = Tsyariah.query.all()
    bayarList= []
    for x in bayar:
        i = x.jml_bayar
        bayarList.insert(0,i)
    bayarList = sum(bayarList)
    if 10000 <= bayarList < 100000:
        bayarList =str(bayarList)[:2]+"K"
    elif 100000 <= bayarList < 1000000:
        bayarList = str(bayarList)[:3]+"K"
    elif bayarList >= 1000000:
        bayarList = bayarList/1000000
        bayarList = round(float(bayarList),2)
        bayarList = str(bayarList)+"M"
    else:
        bayarList = str(bayarList)
    cBayar = "Rp. " + bayarList
    # users = Users.query.with_entities(Users.nik, db.func.count()).all()
    print(cBayar)
    return render_template('dashboard.html',santri=santri,laki=laki,cewe=cewe, cBayar=cBayar)


@radmin.route('/register',methods=['GET','POST'] )
def register():
    form = admin_F()
    if form.validate_on_submit():
        pass_hash = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        add_user = Tusers(username=form.username.data,email=form.email.data, password=pass_hash)
        db.session.add(add_user)
        db.session.commit()
        flash(f'Akun {form.username.data} berhasil terdaftar', 'success')
        return redirect(url_for('radmin.register'))
    return render_template('register.html',form=form)

@radmin.route('/edit_user',methods=['GET','POST'] )
def edit_user():
    form = editadmin_F()
    if form.validate_on_submit():
        pass_hash = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.password = pass_hash
        db.session.commit()
        flash('Data user berhasil diubah', 'success')
        return redirect(url_for('radmin.edit_user'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.password.data = current_user.password
    return render_template('edituser.html',form=form)

@radmin.route('/login',methods=['GET','POST'] )
def login():
    if current_user.is_authenticated:
        return redirect(url_for('radmin.index'))
    form = loginadmin_F()
    if form.validate_on_submit():
        cekemail=Tusers.query.filter_by(email=form.email.data).first()
        if cekemail and bcrypt.check_password_hash(cekemail.password, form.password.data):
            login_user(cekemail)
            print(cekemail)
            return redirect(url_for('radmin.dashboard'))
        else:
            flash('Login Gagal, pastikan email dan password benar', 'danger')
    return render_template('index.html',form=form)

@radmin.route('/logout',)
def logout():
    logout_user()
    return redirect(url_for('radmin.index'))

@radmin.route('/tambah_santri',methods=['GET','POST'] )
@login_required
def tambah_santri():
    form = santri_F()
    if form.validate_on_submit():
        add_santri = Tsantri(nis=form.nis.data, nama_l=form.nama_l.data, jenis_k=form.jenis_k.data, tmpt_l=form.tmpt_l.data,tgl_l=form.tgl_l.data,  alamat=form.alamat.data, th_ajar=form.th_ajar.data, ortu=form.ortu.data,no_hp=form.no_hp.data, status=form.status.data, th_masuk=form.th_masuk.data)
        db.session.add(add_santri)
        db.session.commit()
        flash(f'Santi dengan nama: "{form.nama_l.data}" berhasil ditambahkan!', 'success')
        return redirect(url_for('radmin.tambah_santri'))
    return render_template('santri/tambah_santri.html', form=form)

@radmin.route('/lihat_santri')
@login_required
def lihat_santri():
    santri = Tsantri.query.all()
    return render_template('santri/lihat_santri.html',santri=santri)

@radmin.route('/edit_santri/<int:id>')
@login_required
def updateForm(id):
    form = editsantri_F()
    santri = Tsantri.query.filter_by(id=id).first()
    print(santri)
    return render_template("santri/edit_santri.html", data=santri, form=form)

@radmin.route('/edit_santri', methods=['POST'])
@login_required
def edit_santri():
    if request.method == 'POST':
        id = request.form['id']
        nis = request.form['nis']
        nama_l = request.form['nama_l']
        jenis_k = request.form['jenis_k']
        tmpt_l = request.form['tmpt_l']
        tgl_l = request.form['tgl_l']
        alamat = request.form['alamat']
        th_ajar = request.form['th_ajar']
        ortu = request.form['ortu']
        no_hp = request.form['no_hp']
        status = request.form['status']
        th_masuk = request.form['th_masuk']
        try:
            santri = Tsantri.query.filter_by(id=id).first()
            santri.nis = nis
            santri.nama_l = nama_l
            santri.jenis_k = jenis_k
            santri.tmpt_l = tmpt_l
            santri.tgl_l =tgl_l
            santri.alamat = alamat
            santri.th_ajar = th_ajar
            santri.ortu = ortu
            santri.no_hp = no_hp
            santri.status = status
            santri.th_masuk = th_masuk
            db.session.commit()

        except Exception as e:
            print("Failed to update data")
            print(e)
        return redirect("/lihat_santri")

@radmin.route('/hapus_santri/<int:id>')
@login_required
def hapus_santri(id):
    try:
        santri = Tsantri.query.filter_by(id=id).first()
        db.session.delete(santri)
        db.session.commit()
        flash('Santri berhasil dihapus', 'success')
    except Exception as e:
        print("Failed delete mahasiswa")
        print(e)
    return redirect(url_for('radmin.lihat_santri'))

#BAYAR SYARIAH / SPP PESANTREN
@radmin.route('/tambah_syariah', methods=['GET', 'POST'])
@login_required
def tambah_syariah():
    nomor = request.form.get('nomor')
    santri = Tsantri.query.filter_by(nis=nomor).first()
    ajar = Tajaran.query.all()
    print(santri)
    return render_template('syariah/tambah_syariah.html', santri=santri, ajar=ajar)

@radmin.route('/bayar',methods=['GET','POST'] )
@login_required
def bayar():
    if request.method == 'POST':
        nis = request.form['nis']
        nama_santri = request.form['nama_santri']
        bulan = request.form['bulan']
        tgl_bayar = request.form['tgl_bayar']
        thn_ajaran = request.form['thn_ajaran']
        jml_bayar = request.form['jml_bayar']
        try:
            addBayar = Tsyariah(nis=nis,nama_santri=nama_santri, bulan=bulan, tgl_bayar=tgl_bayar,
            thn_ajaran=thn_ajaran, jml_bayar=jml_bayar)
            db.session.add(addBayar)
            db.session.commit()
        except Exception as e:
            print("Failed to add data.")
            print(e)
    return redirect('/lihat_bayar')


@radmin.route('/lihat_bayar')
@login_required
def lihat_bayar():
    syariah = Tsyariah.query.all()
    return render_template('syariah/lihat_bayar.html', syariah=syariah)

@radmin.route('/edit_syariah/<string:nis>')
@login_required
def bayarForm(nis):
    ajar = Tajaran.query.all()
    syariah = Tsyariah.query.filter_by(nis=nis).first()
    print(syariah)
    return render_template("syariah/edit_syariah.html", syariah=syariah, ajar=ajar)

@radmin.route('/edit_syariah', methods=['POST'])
@login_required
def updateBayar():
    if request.method == 'POST':
        nis = request.form['nis']
        nama_santri = request.form['nama_santri']
        bulan = request.form['bulan']
        tgl_bayar = request.form['tgl_bayar']
        thn_ajaran = request.form['thn_ajaran']
        jml_bayar = request.form['jml_bayar']
        try:
            syariah = Tsyariah.query.filter_by(nis=nis).first()
            syariah.nis = nis
            syariah.nama_santri = nama_santri
            syariah.bulan = bulan
            syariah.tgl_bayar = tgl_bayar
            syariah.thn_ajaran = thn_ajaran
            syariah.jml_bayar = jml_bayar
            db.session.commit()
            flash(f'Pembayaran dengan nama: "{form.nama_santri.data}" berhasil di edit!', 'success')
        except Exception as e:
            print("Failed to update data")
            print(e)
        return redirect('/lihat_bayar')

@radmin.route('/hapus_syariah/<string:nis>')
@login_required
def hapus_syariah(nis):
    try:
        syariah = Tsyariah.query.filter_by(nis=nis).first()
        db.session.delete(syariah)
        db.session.commit()
        flash(f'Pembayaran dengan nama: "{form.nama_santri.data}" berhasil dihapus!', 'success')

    except Exception as e:
        print("Failed delete mahasiswa")
        print(e)
    return redirect(url_for('radmin.lihat_bayar'))


#CRUD TAHUN AJARAN

@radmin.route('/tambah_ajaran', methods=['GET', 'POST'])
def tambah_ajaran():
    if request.method == 'POST':
        # id = request.form['id']
        nama_ajar = request.form['nama_ajar']
        ket_ajar = request.form['ket_ajar']
        try:
            addAjaran = Tajaran(nama_ajar=nama_ajar, ket_ajar=ket_ajar)
            db.session.add(addAjaran)
            db.session.commit()
        except Exception as e:
            print("Failed to add data.")
            print(e)

    return render_template('ajaran/tambah_ajaran.html')

@radmin.route('/lihat_ajaran')

app/templates/eror.html
<h1>Anda Belum Login Bossquee</h1>

app/templates/login.html
{% include "head.html" %}
<title>SIAMA - Login</title>
<body class="bg-gradient-success">

  <!-- Page Wrapper -->
  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image">
                <!-- <img src="{{ url_for('static', filename='img/ipnu.jpg') }}" class="img-fluid" alt="Responsive image"> -->
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back! <br>Sistem Informasi Al Manshuriyah</h1>
                    <!-- <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1> -->
                  </div>
                  <form class="user" action="{{url_for('radmin.login')}}", method="POST">
                    {{form.hidden_tag()}}
                    <div class="form-group">
                      {% with messages = get_flashed_messages(with_categories=true) %}
                      {% if messages %}
                      {% for category, message in messages %}
                        <div class="alert alert-{{category}}">
                          {{message}}
                        </div>
                      {% endfor %}
                      {% endif %}
                      {% endwith %}
                    </div>
                    <div class="form-group">

                        {% if form.email.errors %}
                            {{form.email(class="form-control is-invalid")}}
                            <div class="invalid-feedback">
                              {% for error in form.email.errors %}
                              <span>{{error}}</span>
                              {% endfor %}
                            </div>
                        {% else %}
                            {{form.email(class="form-control form-control-user ", placeholder="Enter Email")}}
                        {% endif %}
                    </div>
                    <div class="form-group">

                        {% if form.password.errors %}
                            {{form.password(class="form-control is-invalid")}}
                            <div class="invalid-feedback">
                              {% for error in form.password.errors %}
                              <span>{{error}}</span>
                              {% endfor %}
                            </div>
                        {% else %}
                            {{form.password(class="form-control form-control-user ", placeholder="Enter password")}}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{form.submit(class="btn btn-success btn-user btn-block")}}
                    </div>
                  </form>

                  <hr>
                  <div class="text-center">
                    <p>Belum punya akun?<br> Silahkan klik tombol dibawah ini</p>
                    <a class="btn btn-primary " href="/register">DAFTAR!</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="#">Forgot Password?</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>



{% include "footer.html" %}

app/templates/nav.html
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Search -->
  <!-- <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form> -->

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <!-- Nav Item - Alerts -->



    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user}}</span>
        <img class="img-profile rounded-circle" src="{{ url_for('static', filename='img/profil.jpg') }}">
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="{{url_for('radmin.edit_user')}}">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Edit User
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Logout
        </a>
      </div>
    </li>

  </ul>

</nav>
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <a class="btn btn-primary" href="{{url_for('radmin.logout')}}">Logout</a>
      </div>
    </div>
  </div>
</div>

app/templates/register.html
{% include "head.html" %}
<title>SIAMA - Register</title>
<body>

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container">
          <br>
          <br>
          <br>
        <div class="container-fluid">
          <h1 class="h3 mb-2 text-gray-800">Pendaftaran User</h1>
          <p class="mb-4">Silahkan masukan  data dengan benar</p>
          <!-- <p class="mb-4">Silahkan klik Tombol disamping untuk mendapatkan infografiknya <a href=""></a></p> -->
          <div class="row">
            <div class="col-xl-12 col-lg-7">
              <!--Flashing -->
              {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{category}}">
                  {{message}}
                  <span> , </span><a href="{{url_for('radmin.login')}}">Kembali ke Login</a>
                </div>
              {% endfor %}
              {% endif %}
              {% endwith %}
                  <div class="card shadow mb-4">



                    <!-- Card Header - Accordion -->
                    <!-- <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
                      <h6 class="m-0 font-weight-bold text-primary">Grabing Tweet</h6>
                    </a> -->
                    <!-- Card Content - Collapse -->
                    <div class="collapse show" id="collapseCardExample">
                      <div class="card-body">
                        <form class="user" action="", method="POST">
                          {{form.hidden_tag()}}
                          <div class="form-group">
                            <!-- {{form.password.label(class="form-control-label")}} -->
                            {% if form.username.errors %}
                                {{form.username(class="form-control form-control-user is-invalid")}}
                                <div class="invalid-feedback">
                                  {% for error in form.username.errors %}
                                  <span>{{error}}</span>
                                  {% endfor %}
                                </div>
                            {% else %}
                                {{form.username(class="form-control form-control-user ", placeholder="Enter username ")}}
                            {% endif %}
                          </div>
                          <div class="form-group">
                            <!-- {{form.password.label(class="form-control-label")}} -->
                            {% if form.email.errors %}
                                {{form.email(class="form-control form-control-user is-invalid")}}
                                <div class="invalid-feedback">
                                  {% for error in form.email.errors %}
                                  <span>{{error}}</span>
                                  {% endfor %}
                                </div>
                            {% else %}
                                {{form.email(class="form-control form-control-user ", placeholder="Enter email")}}
                            {% endif %}
                          </div>
                          <div class="form-group">
                              <!-- {{form.password.label(class="form-control-label")}} -->
                              {% if form.password.errors %}
                                  {{form.password(class="form-control form-control-user is-invalid")}}
                                  <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                    <span>{{error}}</span>
                                    {% endfor %}
                                  </div>
                              {% else %}
                                  {{form.password(class="form-control form-control-user ", placeholder="Enter password")}}
                              {% endif %}
                          </div>
                          <div class="form-group">
                              <!-- {{form.password.label(class="form-control-label")}} -->
                              {% if form.konf_pass.errors %}
                                  {{form.konf_pass(class="form-control form-control-user is-invalid")}}
                                  <div class="invalid-feedback">
                                    {% for error in form.konf_pass.errors %}
                                    <span>{{error}}</span>
                                    {% endfor %}
                                  </div>
                              {% else %}
                                  {{form.konf_pass(class="form-control form-control-user ", placeholder="Ulangi password")}}
                              {% endif %}
                          </div>
                          <div class="form-group">
                              <!-- {{form.username.label(class="form-control-label")}} -->
                              {{form.submit(class="btn btn-success btn-user btn-block")}}
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
            </div>
          </div>
        </div>
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Mas Hadie 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>



{% include "footer.html" %}

app/templates/sidebar.html
<ul class="navbar-nav bg-gradient-success  sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/dashboard">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">SIAMA <sup>0.1</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="{{url_for('radmin.dashboard')}}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Data Santri
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link" href="{{url_for('radmin.tambah_santri')}}">
      <i class="fas fa-fw fa-users"></i>
      <span>Tambah Data Santri</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{url_for('radmin.lihat_santri')}}">
      <i class="fas fa-fw fa-users"></i>
      <span>Lihat Data Santri</span>
    </a>
  </li>
  <!-- Divider -->
  <!-- <hr class="sidebar-divider"> -->

  <!-- Keuangan Sidebar -->
  <!-- <div class="sidebar-heading">
    Keuangan
  </div>

  <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-money-check-alt"></i>
          <span>Master Keuangan</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar" style="">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="#">Lihat Data</a>
            <a class="collapse-item" href="#">Tambah Data</a>
          </div>
        </div>
    </li> -->
  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Pembayaran Syariah
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link" href="{{url_for('radmin.tambah_syariah')}}">
      <i class="fas fa-fw fa-cash-register"></i>
      <span>Transaksi</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{url_for('radmin.lihat_bayar')}}">
      <i class="fas fa-fw fa-cash-register"></i>
      <span>Lihat Data Pembayaran</span>
    </a>
  </li>


  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Tahun Ajaran
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link" href="{{url_for('radmin.tambah_ajaran')}}">
      <i class="fas fa-fw fa-calendar-alt"></i>
      <span>Tambah Tahun Ajaran</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{url_for('radmin.lihat_ajaran')}}">
      <i class="fas fa-fw fa-calendar-alt"></i>
      <span>Lihat Tahun Ajaran</span>
    </a>
  </li>

  <!-- Divider -->
  <!-- <hr class="sidebar-divider"> -->

  <!-- Heading -->
  <!-- <div class="sidebar-heading">
    Data pesantren
  </div> -->
  <!-- Nav Item - Pages Collapse Menu -->
  <!-- <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapse6" aria-expanded="true" aria-controls="collapse6">
          <i class="fas fa-fw fa-cog"></i>
          <span>Data Pesantren</span>
        </a>
        <div id="collapse6" class="collapse" aria-labelledby="heading5" data-parent="#accordionSidebar" style="">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="/edit_pes">Lihat Data</a>
          </div>
        </div>
    </li> -->
  <!-- Nav Item - Charts -->

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>

app/templates/tambah.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Tambah</title>
</head>
<body>
  <form action="/tambah" method="post">
    <input type="text" name='nis'>
    <button type="submit" class="button">Simpan</button>
  </form>
</body>
</html>